### ISSUE TITLE
Error reading from the stream

### ISSUE THREAD

**Issue by hitesh-shukla** [plutext/Docx4j4Android4#8]
`private WordprocessingMLPackage getTemplate(String fileName) {
        AssetManager assetManager = getApplicationContext().getAssets();
        InputStream file;
        WordprocessingMLPackage template = null;
        try {
            file = assetManager.open(fileName);

            template = WordprocessingMLPackage.load(file);

        } catch (IOException e) {
            e.printStackTrace();
        } catch (Docx4JException e) {
            e.printStackTrace();
        }
        return template;
    }`

org.docx4j.openpackaging.exceptions.Docx4JException: Error reading from the stream
 W/System.err:     at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:373)
W/System.err:     at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:345)
W/System.err:     at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:310)
W/System.err:     at org.docx4j.openpackaging.packages.WordprocessingMLPackage.load(WordprocessingMLPackage.java:180)
Caused by: java.io.IOException: Mark has been invalidated.
 W/System.err:     at java.io.BufferedInputStream.reset(BufferedInputStream.java:336)
W/System.err:     at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:371)

**Comment by hitesh-shukla** [comment]
Using
 implementation 'javax.xml.bind:jaxb-api:2.3.0'
    implementation 'javax.xml.stream:stax-api:1.0-2'
    implementation 'com.fasterxml:aalto-xml:1.0.0'
    implementation files('libs/awt-bastardised-17v8.jar')
    implementation files('libs/slf4j-android-1.6.1-RC1.jar')
    implementation files('libs/activation.jar')
    implementation files('libs/additionnal.jar')
    implementation files('libs/jaxb-core-2.3.0-SNAPSHOT-ANDROID.jar')
    implementation files('libs/jaxb-runtime-2.3.0-SNAPSHOT-ANDROID.jar')
    implementation files('libs/istack-commons-runtime-3.0.4-SNAPSHOT.jar')
    implementation files('libs/docx4j-3.3.5-SNAPSHOT2-shaded.jar')
